[tool.poetry]
name = "hello-world"
version = "0.1.0"
description = ""
authors = ["jdenken <jdenken@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.23.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
